export default {
    "login": "provencesl",
    "id": 22637700,
    "node_id": "MDQ6VXNlcjIyNjM3NzAw",
    "avatar_url": "https://avatars.githubusercontent.com/u/22637700?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/provencesl",
    "html_url": "https://github.com/provencesl",
    "followers_url": "https://api.github.com/users/provencesl/followers",
    "following_url": "https://api.github.com/users/provencesl/following{/other_user}",
    "gists_url": "https://api.github.com/users/provencesl/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/provencesl/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/provencesl/subscriptions",
    "organizations_url": "https://api.github.com/users/provencesl/orgs",
    "repos_url": "https://api.github.com/users/provencesl/repos",
    "events_url": "https://api.github.com/users/provencesl/events{/privacy}",
    "received_events_url": "https://api.github.com/users/provencesl/received_events",
    "type": "User",
    "site_admin": false,
    "name": null,
    "company": null,
    "blog": "https://provencesl.github.io/",
    "location": "NanJing",
    "email": null,
    "hireable": null,
    "bio": "VR,Game Developer",
    "twitter_username": null,
    "public_repos": 90,
    "public_gists": 0,
    "followers": 27,
    "following": 209,
    "created_at": "2016-10-05T12:22:36Z",
    "updated_at": "2024-04-28T02:25:00Z"
  }